Small fixes
brunothg/x730-script pull request #3
Opened 2024-12-29 22:16 UTC by radujica

First of all, thank you very much for updating those scripts!

Tested the button on my Pi4 with bookworm raspbian.

The changes here:

- `-b1-13` => `-b1-12` was a fix I found a while back when trying to debug the scripts
- small readme thing

Note: not sure the shutdown / reboot actually work; tried running the reboot once and nothing happened. I don't really need them so did not debug any further.

2025-03-20 10:22 UTC, brunothg requested changes
It's unnecessary to call bash explicitly.
For sure the file needs to be executable (chmod +x).

If you wish to clarify you may add something accordingly to the README.

2025-03-20 10:35 UTC, brunothg requested changes
On my system the date part works just right the way it is.
It's supposed to return a timestamp with millisecond precision.


These are the outputs of your, mine and seconds since Epoche. You're missing one digit?!
174246665745
1742466657453
1742466657

But it might be more robust using a division instead of a truncation.
Also some systems may not support the %N option.

2025-05-25 06:43 UTC, Bond198 commented
I can't find an issues section so I will post it here: journalctl is spammed over and over with:

`
May 25 00:26:02 IPFSPi x730button.sh[160620]: sleep: invalid time interval ‘’
May 25 00:26:02 IPFSPi x730button.sh[160620]: Try 'sleep --help' for more information.
May 25 00:26:02 IPFSPi x730button.sh[160623]: sleep: invalid time interval ‘’
May 25 00:26:02 IPFSPi x730button.sh[160623]: Try 'sleep --help' for more information.
May 25 00:26:02 IPFSPi x730button.sh[160626]: sleep: invalid time interval ‘’
May 25 00:26:02 IPFSPi x730button.sh[160626]: Try 'sleep --help' for more information.
May 25 00:26:02 IPFSPi x730button.sh[160629]: sleep: invalid time interval ‘’
`

Along with constant 30-40% CPU usage. 
![Screenshot 2025-05-25 004151](https://github.com/user-attachments/assets/c1a3348f-58a0-4c14-9035-ed9a48ad194e)

All of my Pi's running Bookworm suddenly have this problem. Buster and Bullseye systems seem unaffected.

Any ideas on how to solve this?

2025-06-07 10:34 UTC, brunothg commented
> I can't find an issues section so I will post it here: journalctl is spammed over and over with:
> 
> `May 25 00:26:02 IPFSPi x730button.sh[160620]: sleep: invalid time interval ‘’ May 25 00:26:02 IPFSPi x730button.sh[160620]: Try 'sleep --help' for more information. May 25 00:26:02 IPFSPi x730button.sh[160623]: sleep: invalid time interval ‘’ May 25 00:26:02 IPFSPi x730button.sh[160623]: Try 'sleep --help' for more information. May 25 00:26:02 IPFSPi x730button.sh[160626]: sleep: invalid time interval ‘’ May 25 00:26:02 IPFSPi x730button.sh[160626]: Try 'sleep --help' for more information. May 25 00:26:02 IPFSPi x730button.sh[160629]: sleep: invalid time interval ‘’`
> 
> Along with constant 30-40% CPU usage. ![Screenshot 2025-05-25 004151](https://private-user-images.githubusercontent.com/5798059/447309202-c1a3348f-58a0-4c14-9035-ed9a48ad194e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDkyOTIzNTMsIm5iZiI6MTc0OTI5MjA1MywicGF0aCI6Ii81Nzk4MDU5LzQ0NzMwOTIwMi1jMWEzMzQ4Zi01OGEwLTRjMTQtOTAzNS1lZDlhNDhhZDE5NGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA2MDdUMTAyNzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzM2YTJkZjA0MjExN2RlYWQ2NzcyODA1Njk0MTczMzI2YTcyYWQ0ZTAyMzYyNjJmYTEyMDZiZjY5ZGYyMDdlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FpA4dRt2MkGQPFR-t64WzBltL6xw1nKuk4tFWKDyIHg)
> 
> All of my Pi's running DietPi Bookworm suddenly have this problem. Buster and Bullseye systems seem unaffected.
> 
> Any ideas on how to solve this?

Your high CPU usage results from failing the sleep command. So this script his hitting your system as hard as possible (but totally unnecessary).

But I cannot tell why this happens in your situation.
Maybe you can figure it out and let us know.
Most likely you have to look at 'src/x730button.sh'  and the declaration of the SLEEPPULSESECONDS variable.

2025-06-09 02:27 UTC, closed without merging